[tool.poetry]
name = "servicenow-sdk-python"
version = "0.1.0"
description = ""
authors = ["dmcanady <dmcanady@liberty.edu>"]
readme = "README.md"
packages = [{include = "servicenow_sdk_python"}]

[tool.poetry.dependencies]
python = "^3.10"
annotated-types = "^0.6.0"
anyio = "^4.2.0"
certifi = "^2023.11.17"
colorama = "^0.4.6"
h11 = "^0.14.0"
httpcore = "^1.0.2"
httpx = "^0.26.0"
idna = "^3.6"
iniconfig = "^2.0.0"
packaging = "^23.2"
pluggy = "^1.3.0"
pydantic = "^2.5.3"
pydantic-core = "^2.14.6"
sniffio = "^1.3.0"
typing-extensions = "^4.9.0"
uritemplate = "^4.1.1"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
